export const FETCH_RENTALS_INIT = "FETCH_RENTALS_INIT";
export const FETCH_RENTALS = "FETCH_RENTALS";
export const FETCH_RENTALS_BY_ID = "FETCH_RENTALS_BY_ID";
export const DELETE_RENTAL = "DELETE_RENTAL";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_BOOKINGS_INIT = "FETCH_BOOKINGS_INIT";
export const FETCH_BOOKINGS = "FETCH_BOOKINGS";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
